services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app                # Copy everything from the repo to /app in the container
      - /app/node_modules     # ...Except the node modules folder (we want a fresh one)
      - /app/.yarn            # .. and also the .yarn folder (we also want a fresh one of those)
    environment:
      - CHOKIDAR_USEPOLLING=true
